### ISSUE TITLE
Single image haze removal using dark channel prior

### ISSUE THREAD

**Issue by yyfyan** [chaimi2013/FAMED-Net#2]
Best job! 
Now I meet some problem, the DCP dehaze is classical algorithm, but I not find the official code. How do you test this algorithm in your paper. I want to test it now, can you help me, thanks.

**Comment by chaimi2013** [comment]
> Best job!
> Now I meet some problem, the DCP dehaze is classical algorithm, but I not find the official code. How do you test this algorithm in your paper. I want to test it now, can you help me, thanks.

The implementation of DCP is straightforward.  You may use guided filter for a fast running speed rather than the softmatting.
